config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  resources :users

  resources :projects do
    resources :tickets
  end

  resources :purchases

  namespace :admin do
    root "base#index"
    resources :users
  end
  
  root "projects#index"
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tickets, dependent: :delete_all
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :project
	belongs_to :user

	validates :title, presence: true
	validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tickets

	has_secure_password

	validates :username, presence: true
	validates :email, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authorize_admin!

	def index
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

	def index
		@users = User.order(:email)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash.notice = "User created."
			redirect_to admin_users_path
		else
			flash.now.notice = "Error creating user."
			render :new
		end
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
      def authorize_admin!
      require_login

      unless current_user.admin?
        flash[:notice] = "Admin account required."
        redirect_to root_path
      end
    end
end

app/controllers/concerns/session_management.rb
module SessionManagement
	extend ActiveSupport::Concern

	def require_login
		if current_user.nil?
			flash[:notice] = "Please login."
			redirect_to login_url
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SessionManagement

  before_action :authorize_admin!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project has been created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project has been updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project has been destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit([:name, :description])
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:name, :cost)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.where(:username => params[:login][:username]).first

		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id
			flash[:notice] = "Hi, #{user.username}!"

			redirect_to root_url
		else
			flash[:notice] = "Incorrect login."
			render :new
		end
	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	include SessionManagement

	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	before_action :require_login, except: [:show, :index]

	helper_method :require_login
	helper_method :current_user

	def new
		@ticket = @project.tickets.build
	end

	def create
		@ticket = @project.tickets.build(ticket_params)
		@ticket.user = current_user

		if @ticket.save
			flash[:notice] = "Ticket created."
			redirect_to [@project, @ticket]
		else
			flash[:notice] = "Error creating ticket."
			render :new
		end
	end

	def edit
	end

	def update
		if @ticket.update(ticket_params)
			flash[:notice] = "Ticket updated."

			redirect_to [@project, @ticket]
		else
			flash[:notice] = "Error updating ticket."

			render :edit
		end
	end

	def destroy
		@ticket.destroy
		flash[:notice] = "Ticket deleted."

		redirect_to @project
	end

	private
		def ticket_params
			params.require(:ticket).permit(:title, :description)
		end

		def set_project
			@project = Project.find(params[:project_id])
		end

		def set_ticket
			@ticket = @project.tickets.find(params[:id])
			@ticket.user = current_user
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:notice] = "Welcome, #{@user.username}!"
			redirect_to projects_path
		else
			flash[:notice] = "Error with your input."
			render :new
		end
	end

	private

		def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def admin_only(&block)
		block.call if current_user.try(:admin?)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<p id="notice"><%= notice %></p>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

		<p>
		<%= f.label :username %><br>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>

	<%= f.submit "Submit" %>
<% end %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul id="users">
	<% @users.each do |user|
		<li><%= link_to user.email, [:admin, user] %></li>
	<% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<p>
			<%= current_user.username %>
			<% admin_only do %>
				<%= link_to "Admin", admin_root_path %>
			<% end %>
		</p>
	<% else %>
		<p>
			<%= link_to "Login", login_path %> | 
			<%= link_to "Sign up", new_user_path %>
		</p>
	<% end %>

	<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <p id="notice"><%= notice %></p>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name%><br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= truncate(project.description, :length => 25, :separator => ' ') %></td>
        <% admin_only do %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
           <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% admin_only do %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @project.name %></h2>
<p><%= simple_format(@project.description) %></p>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			<%= link_to ticket.title, project_ticket_path(@project, ticket) %> (#<%= ticket.id %>)<br>
			<span class="author">Added by <%= ticket.user.username %></span><br>
			<%= link_to "Edit", edit_project_ticket_path(@project, ticket) %> |
			<%= link_to "Delete", project_ticket_path(@project, ticket), method: :delete, data: { confirm: "Are you sure?" } %>
		</li>
	<% end %>
</ul>

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.name %></td>
        <td><%= purchase.cost %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @purchase.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @purchase.cost %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
		<% if @ticket.errors.any? %>
		<div id="error_explanation">
			<p id="notice"><%= notice %></p>
			<ul>
				<% @ticket.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>

	<%= f.submit "Submit" %>
<% end %>

app/views/tickets/edit.html.erb
<p id="notice"><%= notice %></p>

<h2>Edit Ticket</h2>

<%= render "form" %>

app/views/tickets/new.html.erb
<p id="notice"><%= notice %></p>

<h2>New Ticket</h2>

<%= render "form" %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<div id="ticket">
	<h3><%= @ticket.title %></h3>
	<span class="author">Added by <%= @ticket.user.username %></span>
	<%= simple_format(@ticket.description) %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<p id="notice"><%= notice %></p>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :username %><br>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>

	<%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render "form" %>